### PR TITLE
fix: Spinner animation overwrites error message

### LINKED ISSUE #82: Loader/spinner not correctly hidden when rendering an error message
Extracted this part from #67 

image

It seems the loader/spinner output displayed while the command is running is only partially overwritten by an error message occurring during the run (see the breakup of red to white text).

I've had a quick look at the code that I though would be responsible for it, but couldn't spot anything "obviously" wrong, i.e. it seems to explicitly handle exceptions from running commands
https://github.com/meshcloud/collie-cli/blob/6fec4d02477ee3f8cf81a2b846ce9c7989110b12/src/process/loader-shell-runner.ts#L19-L29

This probably needs a more thorough investigation.

### PR DESCRIPTION
**Pull request by tfelix**
Improves the spinner animation termination to avoid part of the error message
writing into the spinner animation text.

Fixes #82

### CODE REVIEW

File: src/process/loader-shell-runner.ts [hunk 1]
```diff
@@ -71,8 +73,20 @@ export class LoaderShellRunner implements IShellRunner {
     this.tty.showCursor();
   }
 
+  /**
+   * In case of an exception you probably want to force stop the loading animation. Oftherwise the parallel
```
Comment (JohannesRudolph) [inline src/process/loader-shell-runner.ts:77]: parallel -> concurrently?

File: src/process/loader-shell-runner.ts [hunk 2]
```diff
@@ -71,8 +73,20 @@ export class LoaderShellRunner implements IShellRunner {
...
+   * This just ignores the commands running in the background and kills off the animation right away.
+   */
+  private forceStopLoading() {
+    this.runningCommandsCount = 0;
+    this.stopLoading();
+  }
+
   private stopLoading() {
-    this.runningCommandsCount--;
+    if (this.runningCommandsCount > 0) {
```
Comment (JohannesRudolph) [inline src/process/loader-shell-runner.ts:87]: I assume this is just defensive coding, we don't expect that there are legitimate situations in which we decrease runningCommandsCount below zero, right -> except when we do a forceStopLoading, right?

Comment (JohannesRudolph) [reply src/process/loader-shell-runner.ts:87]: a comment in the code with that as explanation might be helpful

File: src/process/loader-shell-runner.ts [hunk 3]
```diff
@@ -71,8 +73,20 @@ export class LoaderShellRunner implements IShellRunner {
...
+      this.runningCommandsCount--;
+    }
     if (this.runningCommandsCount > 0) {
       return;
     }
```
Comment (JohannesRudolph) [inline src/process/loader-shell-runner.ts:92]: meta: maybe the readability of this class can be slightly improved/refactored by separating the loader presentation from the loader logic/controller.

**Review by JohannesRudolph — APPROVED** [review]

File: src/process/loader-shell-runner.ts (hunk 1 above)
Comment (tfelix) [reply src/process/loader-shell-runner.ts:77]: Changed.

File: src/process/loader-shell-runner.ts (hunk 2 above)
Comment (tfelix) [reply src/process/loader-shell-runner.ts:87]: add a comment.

File: src/process/loader-shell-runner.ts (hunk 3 above)
Comment (tfelix) [reply src/process/loader-shell-runner.ts:92]: I once worked upon it a bit, but its a bit chaotic since you need to have some wild jumps between the blocks. I guess for now its okaish as I hope this class does not need to be touched anymore. :D But we need to keep that in mind if it gets even more complicated we should rework its implementation.
